---
- name: resolve platform specific vars
  include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: install dnsmasq with package manager
  become: '{{ dnsmasq_privilege_escalate }}'
  become_user: root
  package:
    name: dnsmasq
    state: present
- name: post-installation operations
  become: '{{ dnsmasq_privilege_escalate }}'
  become_user: root
  when: not dnsmasq_install_pkg_only
  block:
    - name: disable_systemd_resolved
      when: dnsmasq_disable_systemd_resolved
      service:
        name: systemd-resolved
        state: stopped
        enabled: no
    - name: activate dnsmasq service
      when: dnsmasq_activate
      service:
        name: dnsmasq
        state: started
        enabled: yes
